[package]
name = "rusty-camino"
version = "0.1.0"
authors = ["epsniff <epsniff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rs-camino"
path = "src/main.rs"


[dependencies]
clap = "2.33.0"
env_logger = "0.3"
hyper = "0.13.3"
tokio = "0.2.13"
futures = "0.3.4"
